# Generated by Django 3.1.5 on 2021-01-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.CharField(default='', max_length=500)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
